In [2]:
#importing basic packages
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [3]:
bank=pd.read_csv('Bank-data.csv')

In [4]:
bank.head()

Index  interest_rate  credit  Gender  previous  duration Churn
0      0          1.334       0       1         0       117    no
1      1          0.767       0       0         1       274   yes
2      2          4.858       0       1         0       167    no
3      3          4.120       0       0         0       686   yes
4      4          4.856       0       1         0       159    no

In [ ]:
#No need to handle outlier ,missing value,feature scaling -PCA will take care and also if any variable is not needed ,dont drop that 
#just delete non-significant values and PCA will determine which values are significant or non-significant

In [5]:
#Converting dependent variable into 0 and 1
bank['Churn']=bank['Churn'].astype('category')
bank['Churn']=bank['Churn'].cat.codes

In [6]:
bank.head()

Index  interest_rate  credit  Gender  previous  duration  Churn
0      0          1.334       0       1         0       117      0
1      1          0.767       0       0         1       274      1
2      2          4.858       0       1         0       167      0
3      3          4.120       0       0         0       686      1
4      4          4.856       0       1         0       159      0

In [ ]:
#Splitting the data into x and y

In [7]:
x=bank.drop(['Churn'],axis=1)

In [8]:
y=bank['Churn']

In [9]:
x.head()

Index  interest_rate  credit  Gender  previous  duration
0      0          1.334       0       1         0       117
1      1          0.767       0       0         1       274
2      2          4.858       0       1         0       167
3      3          4.120       0       0         0       686
4      4          4.856       0       1         0       159

In [10]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: Churn, dtype: int8

In [11]:
#Splitting data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75,random_state=101)

In [12]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
logit=LogisticRegression()
logit.fit(x_train,y_train)

LogisticRegression()

In [13]:
y_pred_logit_test=logit.predict(x_test)

In [14]:
#Evaluation
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [15]:
print(classification_report(y_test,y_pred_logit_test))

              precision    recall  f1-score   support

           0       0.85      0.86      0.86        66
           1       0.86      0.84      0.85        64

    accuracy                           0.85       130
   macro avg       0.85      0.85      0.85       130
weighted avg       0.85      0.85      0.85       130



In [16]:
print(confusion_matrix(y_test,y_pred_logit_test))

[[57  9]
 [10 54]]


In [17]:
print(accuracy_score(y_test,y_pred_logit_test))

0.8538461538461538


In [ ]:
#Without doing any preprocessing and PCA ,here accuracy is 85.3% 

In [ ]:
#Here so many non significant variables like Index,outlier etc

In [ ]:
#Principal Component Analysis

In [18]:
from sklearn.decomposition import PCA
pca=PCA(n_components=None)
x_train_n=pca.fit_transform(x_train)
x_test_n=pca.fit_transform(x_test)

In [19]:
x_train_n

array([[-2.93378624e+02,  1.75880375e+02,  1.20450607e+00,
        -2.17952821e-01, -5.86169904e-02, -6.43952806e-02],
       [ 7.45993427e+01,  2.80611960e+00, -1.36133278e+00,
        -2.39815581e-01, -2.75379051e-01, -6.54049847e-02],
       [ 6.71224555e+01, -1.29723788e+02, -1.78564425e+00,
        -4.02307304e-01,  6.60349989e-01, -7.18312246e-02],
       ...,
       [-1.70538962e+02, -1.42453138e+02, -1.98178359e+00,
        -2.29513539e-01, -3.44537504e-01, -6.34838765e-02],
       [-2.64117844e+02,  1.71315922e+02, -1.66158580e+00,
         7.78327477e-01, -1.06204628e-01, -5.62070746e-02],
       [-1.54322261e+02, -8.55844804e+01, -1.32132983e+00,
        -2.30250412e-01, -2.87148059e-01, -6.11096622e-02]])

In [20]:
pd.DataFrame(x_train_n)

0           1         2         3         4         5
0   -293.378624  175.880375  1.204506 -0.217953 -0.058617 -0.064395
1     74.599343    2.806120 -1.361333 -0.239816 -0.275379 -0.065405
2     67.122455 -129.723788 -1.785644 -0.402307  0.660350 -0.071831
3    245.440861   10.235364 -2.157012 -0.246891 -0.331914 -0.071690
4     15.697036   39.948247 -1.234058 -0.283169 -0.248414  0.928485
..          ...         ...       ...       ...       ...       ...
383  -32.672437  147.695008 -1.237047 -0.431870  0.760952  0.895611
384  601.721110  -27.248123  2.193456 -0.289801 -0.029500  0.005303
385 -170.538962 -142.453138 -1.981784 -0.229514 -0.344538 -0.063484
386 -264.117844  171.315922 -1.661586  0.778327 -0.106205 -0.056207
387 -154.322261  -85.584480 -1.321330 -0.230250 -0.287148 -0.061110

[388 rows x 6 columns]

In [21]:
explained_variance=pca.explained_variance_ratio_

In [22]:
explained_variance#more the value that much significant that slice or column is

array([8.07144870e-01, 1.92823493e-01, 2.92532511e-05, 1.52261165e-06,
       6.96408766e-07, 1.64823601e-07])

In [ ]:
#first slice giving ~80.7%
#second slice giving ~19.2%
#third slice giving (non-significant)
#fourth slice giving(non-significant)
#fifth slice giving (non-significant)
#sixth slice giving (non-significant)


In [23]:
pca=PCA(n_components=2)
x_train_2=pca.fit_transform(x_train)
x_test_2=pca.fit_transform(x_test)

In [24]:
pd.DataFrame(x_train_2)

0           1
0   -293.378624  175.880375
1     74.599343    2.806120
2     67.122455 -129.723788
3    245.440861   10.235364
4     15.697036   39.948247
..          ...         ...
383  -32.672437  147.695008
384  601.721110  -27.248123
385 -170.538962 -142.453138
386 -264.117844  171.315922
387 -154.322261  -85.584480

[388 rows x 2 columns]

In [25]:
#Now Build Model
logit_1=LogisticRegression()
logit_1.fit(x_train_2,y_train)

LogisticRegression()

In [26]:
y_pred_pca_logit1=logit_1.predict(x_test_2)

In [33]:
y_pred_pca_logit1_train=logit_1.predict(x_train_2)

In [35]:
print(accuracy_score(y_train,y_pred_pca_logit1_train))

0.6804123711340206


In [28]:
print(accuracy_score(y_test,y_pred_pca_logit1))#Accuracy reduced becuae 80%of the information we removed because of PCA

0.7384615384615385


In [45]:
#To improve accuracy-K-fold method
from sklearn.model_selection import cross_val_score
accuracy_train=cross_val_score(logit_1,x_train_2,y_train,cv=10)
accuracy_test=cross_val_score(logit_1,x_test_2,y_test,cv=10)
print(accuracy_train[7])
print("#####"*20)
print(accuracy_test[6])

0.8205128205128205
####################################################################################################
0.9230769230769231


In [ ]:
#Naive Bayes Theorem

In [46]:
from sklearn.naive_bayes import GaussianNB

In [47]:
classifier_nb=GaussianNB()
classifier_nb.fit(x_train_2,y_train)

GaussianNB()

In [48]:
y_pred_nb=classifier_nb.predict(x_test_2)

In [49]:
print(accuracy_score(y_test,y_pred_nb))

0.676923076923077


In [ ]:
#K-fold 

In [61]:
accuracy_nb=cross_val_score(classifier_nb,x_test_2,y_test,cv=15)

In [63]:
print(accuracy_nb[8])

0.8888888888888888
